import type { RangeEntry } from '@/data/types'
import { parseRangeEntries } from './rangeEntries'
import {
  effectiveOpenSize,
  FORMAT_LABELS,
  RANGE_TYPE_LABELS,
  type Format,
  type GameSetup,
  type OpenSize,
  type RangeType,
  type Stack,
} from './scenarios'

/** A built-in set of charts, generated by scripts/build-ranges.mjs into public/ranges/<id>.json. */
export interface RangeSet {
  id: string
  format: Format
  stack: Stack
  rangeType: RangeType
  /** Set when the charts were solved for one specific open size. */
  openSize?: OpenSize
}

/** Keep in sync with the SETS table in scripts/build-ranges.mjs. */
export const RANGE_SETS: readonly RangeSet[] = [
  { id: 'Cash_100_PTO', format: 'cash', stack: 100, rangeType: 'pto' },
  { id: 'Cash_100_Simple', format: 'cash', stack: 100, rangeType: 'simple' },
  { id: 'Cash_100_PRO', format: 'cash', stack: 100, rangeType: 'pro' },
  { id: 'Cash_100_GTO', format: 'cash', stack: 100, rangeType: 'gto', openSize: 2.5 },
  { id: 'Cash_100_GTO_2bb', format: 'cash', stack: 100, rangeType: 'gto', openSize: 2 },
  { id: 'Cash_100_GTO_3bb', format: 'cash', stack: 100, rangeType: 'gto', openSize: 3 },
  ...([100, 40, 20, 10, 5] as const).flatMap((stack): RangeSet[] => [
    { id: `MTT_${stack}_PTO`, format: 'mtt', stack, rangeType: 'pto' },
    { id: `MTT_${stack}_GTO`, format: 'mtt', stack, rangeType: 'gto' },
  ]),
]

export function rangeSetFor(setup: GameSetup): RangeSet | undefined {
  const openSize = effectiveOpenSize(setup)
  return RANGE_SETS.find(
    (s) =>
      s.format === setup.format &&
      s.stack === setup.stack &&
      s.rangeType === setup.rangeType &&
      (s.openSize === undefined || s.openSize === openSize),
  )
}

export function rangeSetLabel(set: RangeSet): string {
  const open = set.openSize !== undefined ? ` ${set.openSize}bb open` : ''
  return `${FORMAT_LABELS[set.format]} ${set.stack}bb ${RANGE_TYPE_LABELS[set.rangeType]}${open}`
}

export function rangeSetUrl(id: string): string {
  return `/ranges/${id}.json`
}

const cache = new Map<string, Promise<RangeEntry[]>>()

/** Fetch and validate a built-in set. Results are cached for the lifetime of the page. */
export function loadRangeSet(id: string): Promise<RangeEntry[]> {
  let pending = cache.get(id)
  if (!pending) {
    pending = fetch(rangeSetUrl(id))
      .then((res) => {
        if (!res.ok) throw new Error(`Could not load range set ${id} (${res.status}).`)
        return res.text()
      })
      .then(parseRangeEntries)
    pending.catch(() => cache.delete(id))
    cache.set(id, pending)
  }
  return pending
}
